INSERT INTO `jobs` (name, label) VALUES
  ('offpolice','Off-Duty'),
  ('offambulance','Off-Duty'),
  ('offfire','Off-Duty'),
  ('offmecano','Off-Duty')
;

INSERT INTO `job_grades` (job_name, grade, name, label, salary, skin_male, skin_female) VALUES
 ('offpolice', 0, 'recruit', 'Cadet', 350, '{}', '{}'),
 ('offpolice', 1, 'officer', 'Officer I', 650, '{}', '{}'),
 ('offpolice', 2, 'officer2', 'Officer II', 700, '{}', '{}'),
 ('offpolice', 3, 'deputy', 'Deputy I', 650, '{}', '{}'),
 ('offpolice', 4, 'deputy2', 'Deputy II', 700, '{}', '{}'),
 ('offpolice', 5, 'trooper', 'Trooper', 800, '{}', '{}'),
 ('offpolice', 6, 'lspdcpl', 'LSPD-Cpl', 800, '{}', '{}'),
 ('offpolice', 7, 'lsbcsocpl', 'LSBCSO-Cpl', 800, '{}', '{}'),
 ('offpolice', 8, 'sastcpl', 'SAST-Cpl', 900, '{}', '{}'),
 ('offpolice', 9, 'sergeant', 'Sgt-PD', 900, '{}', '{}'),
 ('offpolice', 10, 'sergeantso', 'Sgt-SO', 900, '{}', '{}'),
 ('offpolice', 11, 'sergeantst', 'Sgt-ST', 1000, '{}', '{}'),
 ('offpolice', 12, 'intendent', 'int', 600, '{}', '{}'),
 ('offpolice', 13, 'lieutenant', 'LSPD-Lt', 1000, '{}', '{}'),
 ('offpolice', 14, 'lieutenantso', 'LSPBCSO-Lt', 1000, '{}', '{}'),
 ('offpolice', 15, 'lieutenantst', 'SAST-Lt', 1250, '{}', '{}'),
 ('offpolice', 16, 'captain', 'LSPD-Cpt', 1250, '{}', '{}'),
 ('offpolice', 17, 'captainso', 'LSBCSO-Cpt', 1250, '{}', '{}'),
 ('offpolice', 18, 'astchef', 'Ast Chief', 1500, '{}', '{}'),
 ('offpolice', 19, 'depsher', 'Dep Sheriff', 1500, '{}', '{}'),
 ('offpolice', 20, 'chef', 'PD-Chief', 1000, '{}', '{}'),
 ('offpolice', 21, 'sheriff', 'Sheriff', 1000, '{}', '{}'),
 ('offpolice', 22, 'boss', 'Dept Head', 1750, '{}', '{}'),
  ('offambulance',0,'ambulance','Ambulance',500,'{}','{}'),
  ('offambulance',1,'doctor','Doctor',500,'{}','{}'),
  ('offambulance',2,'chief_doctor','Chief Doctor',650,'{}','{}'),
  ('offambulance',3,'boss','Boss',1000,'{}','{}'),
 ('offfire', 0, 'recruit', 'Jr FF/EMT', 350, '{}', '{}'),
 ('offfire', 1, 'sergeant', 'FF/EMT', 650, '{}', '{}'),
 ('offfire', 2, 'lieutenant', 'Bt. Chief', 800, '{}', '{}'),
 ('offfire', 3, 'boss', 'FD-Chief', 1750, '{}', '{}'),
  ('offmecano',0,'recrue','Technician',500,'{}','{}'),
  ('offmecano',1,'novice','Technician',500,'{}','{}'),
  ('offmecano',2,'experimente','Technician',500,'{}','{}'),
  ('offmecano',3,'chief','Chef déquipe',650,'{}','{}'),
  ('offmecano',4,'boss','Patron',1000,'{}','{}')
;