Citizen.CreateThread(function()
    TriggerEvent('chat:addSuggestion', "/me", "")
    TriggerEvent('chat:addSuggestion', "/ooc", "Talk Out Of Character")
    TriggerEvent('chat:addSuggestion', "/trev", "Send a message as trevor to the server")
    TriggerEvent('chat:addSuggestion', "/ld", "Send a message as Lamar to the server")
    TriggerEvent('chat:addSuggestion', "/hud", "removes job hud")
    TriggerEvent('chat:addSuggestion', "/sit", "sit on closest chair")
    TriggerEvent('chat:addSuggestion', "/rob", "steal from a player")
end)